### ISSUE TITLE
Install the nuget package does not add the folders or files

### ISSUE THREAD

**Issue by ravenboilinux** [kip-dk/dynamics-plugin#4]
I was really interested in using this package to help me with plugin creation. I was going thru the step by step guide, and after "Install the Kipon.Solid nuget package", I noticed there was nothing in my C# project

**Comment by kip-dk** [comment]
Hi raven
could you share some more details. The concept is used at lot around without issues. Are you using the newest version 9.0.9.3.
(require at least version 9.0 Dynamics 365 CE installation)

did your project start as a C# .NET Framework class library version 4.6.2 (.NET Core is NOT supported), and you cannot go higher than 4.6.2. 

What version of visual studio are you using.

Finally, visual studio might have to run with admin priviliges (run as administrator). I am not sure about that, but i have seen different types of issues if you just run visual studio without it.

**Comment by kip-dk** [comment]
I have just tested with Visual Studio version 17.1.6, and found no issues:

![image](https://user-images.githubusercontent.com/8783399/194997544-6fd9fda7-dc42-4ac4-b297-2d45d516a9fd.png)

And after installing nuget package:

![image](https://user-images.githubusercontent.com/8783399/194997592-40db04bd-0c95-4c7b-ae47-67a70593b07f.png)

**Comment by ravenboilinux** [comment]
That leaves me to ask what version of Visual Studio since I have most up to date version of visual studio 2019 and it is version 16.11.17

**Comment by ravenboilinux** [comment]
I have tried it vs2020 and same thing happens. It show me the read me file but the read me file is located in my .nuget folder in my user folder. Which does look like the folders and files are.
![image](https://user-images.githubusercontent.com/4099274/195070275-78402a93-2694-496b-94c7-483c29ca1259.png)

**Comment by kip-dk** [comment]
visual studio is fine 2019 is fine.  (I am using visual studio 2022, but i switch from 2019 not that long ago, and that works fine)

Could you see if the files are added on the file system, and just hidden in the class library structure.

If for some reason your visual studio things that the class library it is a .NET core library, files will not be added, so please also make sure that the classlibrary is .NET Framework version 4.6.2.

Also -.. is it visual studio **code** you are using, (i have never tried that), only  visual studio community, professional and enterprise

**Comment by ravenboilinux** [comment]
visual studio community is the version I am using, just with dark mode turn on. I did check if file where in the file system but not in the projects. The files are not in the folder for the class lib project. :( 
![image](https://user-images.githubusercontent.com/4099274/195088083-a131297c-151c-4b0f-a15a-7b79dc0dea11.png)
![image](https://user-images.githubusercontent.com/4099274/195088160-63c3b9b5-075c-400d-a6a8-5de72b02c87d.png)

**Comment by kip-dk** [comment]
Really strange, could you take a screen dump of the class lib settings:

it should look like this:

![image](https://user-images.githubusercontent.com/8783399/195091751-9f6e61cc-996d-45da-b7d6-436876cff51e.png)

And your nuget settings for the library should look like this:

![image](https://user-images.githubusercontent.com/8783399/195092164-932660e8-75e8-4695-8dc7-985dcd207eb2.png)

Finally could you check that the visual studio process has write access to the project folder. (i have never experienced this type of issue, so i am grapping in the air)

**Comment by ravenboilinux** [comment]
![image](https://user-images.githubusercontent.com/4099274/195094732-7cef40ca-1390-4fd5-9704-580c7c72fb74.png)
![image](https://user-images.githubusercontent.com/4099274/195094784-1dda3ead-9bb8-4926-816f-4c309dae8d06.png)

**Comment by ravenboilinux** [comment]
what is the visual studio process that writes the files?

**Comment by kip-dk** [comment]
The library is not installed, there should be a version

![image](https://user-images.githubusercontent.com/8783399/195095728-28a54ac6-557c-4274-b0e2-898b7ebb761e.png)

And i am not sure why the project is stated as a folder structure. In my solution is simply states the plugin library name.

Did you create the solution and the class library in same folder? (not sure if that is a problem)

I am currently installing visual studio 2022 community on a clean pc, and i will test there

**Comment by kip-dk** [comment]
did you start visual studio with admin priviliges. If not, you could try that. it might help.  [Shift] + [right click] run as admin, and then try install the package again.

**Comment by ravenboilinux** [comment]
It is installed into the class lib
![image](https://user-images.githubusercontent.com/4099274/195097429-54cb0dc5-ddf1-492c-8d31-e4148b6cd344.png)

and visual studio is running under admin priviliges

**Comment by kip-dk** [comment]
What does the red cross beside 1.0.9.3 mean, i do not have that, and in your earlier screen dump, the right side of the nuget package state did not state any version on the class library for the kipon solid plugin lib.

![image](https://user-images.githubusercontent.com/8783399/195100424-a1fbb06b-3621-45d0-9f38-73a71cca538c.png)

I am continue installing the community edition on a clean pc, so lets see if i can provoke similar problem there.

**Comment by ravenboilinux** [comment]
So you are looking at nuget from the solution level in screen shot.
I did send screen shot from the solution level, but you said that your package was not installed in to the class lib. 
So I sent you a screen shot neget packages in the class lib from the project level. The red cross is the delete button, pressing that button will delete that package from the project. Typically I will use the project level ui for handling package for a single project, and use the solution level ui for solution with many project in them.

**Comment by ravenboilinux** [comment]
Here is a video of the adding the package

https://user-images.githubusercontent.com/4099274/195136813-d636a125-7c82-4bb9-b7e4-3e8a1b3edbf0.mp4

**Comment by kip-dk** [comment]
Thanks for sharing. I will test with a plain new visual studio community edition later today, and create a full video capture.

In means time could you see if there is anything in the output window given us a clue:

![image](https://user-images.githubusercontent.com/8783399/195254378-82d4510a-a16f-4df5-8e67-8bd65d964537.png)

**Comment by kip-dk** [comment]
I tried the following with success:

Install visual studio 2022 community edition on a pc that never had it before

![image](https://user-images.githubusercontent.com/8783399/195274078-eed85cfe-91e3-495f-a64a-f32f3d0effda.png)


Reboot as request by installation
Open visual studio run as admin
Start without code
Create new project of type .NET Framework class lib 4.6.2
Add nuget.org to package management system (it was not there by default)
Add nuget package kipon.solid from nuget.org package source with reference to the class lib
Accept license terms on kipon and microsoft sdk packages.

After that i had a correct project with everything correctly setup for me, ready to adjust the template files according to the installation guide.

![image](https://user-images.githubusercontent.com/8783399/195273511-15c7797d-3e62-4cd0-b857-11a9c7607e91.png)

I hope that the output log in your end can give us some clue on the problem, because i am running out of idears.

**Comment by ravenboilinux** [comment]
![image](https://user-images.githubusercontent.com/4099274/195286565-d6c2e340-f3d8-469e-bd14-d946eb2533e4.png)
This is what I got from Package Manager

**Comment by ravenboilinux** [comment]
Here is my about MS VS information too

Microsoft Visual Studio Community 2019
Version 16.11.17
VisualStudio.16.Release/16.11.17+32630.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-00000-00000-AA717
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.126+g11d4cf0d0c.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

SQL Server Reporting Services   15.0.19528.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19528.0

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by kip-dk** [comment]
Your installation is clearly installing fewer libraries - compared with my log. I have no idea why.

Could you by any chance try to install visual studio 2022 community edition (they can live side by side with 2019). And start with a totally new project from stratch.

I will create and post a video with the full process on the documentation site later today

**Comment by kip-dk** [comment]
Could it be something related to how you manage package

This article is saying something about that. I have not tested the nuget installation process using "[PackageReference](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)"

style, so that might be the issue.

https://github.com/NuGet/Home/issues/8718

**Comment by kip-dk** [comment]
I think it is related to package management method:

![image](https://user-images.githubusercontent.com/8783399/195302166-a3c71d95-e283-4c37-a349-c73181684f53.png)

The files are deployed using the content folder that is not supported for this packagereference model.

I will start work on a solution that solves the problem.

For now you can try ensure you are using the package.json approach for you project (se how to rollback below)

https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

Thanks for your input.

**Comment by kip-dk** [comment]
Bingo. The kipon.solid plugin framework does not yet support PackageReference nuget installation process, i will work on it and close this issue when there is a fix.

Until then you do have the option to switch back your package management process to package.json, before creating your kipon.solid plugin solution:

![image](https://user-images.githubusercontent.com/8783399/195307101-8ceca986-ae6a-480a-bfdc-74b46cb24f89.png)

**Comment by ravenboilinux** [comment]
Changing back to package.json, and creating a new class lib did the trick. 

One thing you should also look into is the new feature of package dependency in the Dataverse. It is in the 2022 wave r2 as preview. It allows you include package the whole plugin as a nuget package. Allowing devs to now include dependent assemblies with their plugin. No more having to ILMerge a bunch of dlls together.

**Comment by kip-dk** [comment]
Hi 

i am happy that it worked out for you. I am looking at the new package dependency in the Dataverse approach, and that will actually allow me to distribute kipon.solid as a compiled DLL, rather than an accumulated cs file.  The main reason it is currently distributed as source code and included in the plugin library  is to avoid having to use ILMerge. Ofcause if you are already merging libraries into your plugin library, the advantage of that approach is limited.
